# ──────────────────────────────────────────────────────────────────────────────
# ProGuard / R8 rules for المنشاوي: المرتل والنوادر
# ──────────────────────────────────────────────────────────────────────────────
# Flutter's R8/ProGuard pipeline already includes rules for the Dart AOT runtime
# via the Flutter Gradle plugin. These supplemental rules protect the Java/Kotlin
# layers of the plugins used by this app.
# ──────────────────────────────────────────────────────────────────────────────

# ── Flutter engine & plugins ──────────────────────────────────────────────────
-keep class io.flutter.app.**       { *; }
-keep class io.flutter.plugin.**   { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.plugins.**
-keep class io.flutter.util.**     { *; }
-keep class io.flutter.view.**     { *; }
-keep class io.flutter.**          { *; }

# ── Google Play Core (deferred components / dynamic delivery) ──────────────────
# Flutter's engine references these for Play Store dynamic feature delivery.
# They are absent in regular APK builds — suppress R8 "Missing class" errors.
# (Rules auto-generated by R8 from build/app/outputs/mapping/release/missing_rules.txt)
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.SplitInstallException
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManager
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManagerFactory
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest$Builder
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest
-dontwarn com.google.android.play.core.splitinstall.SplitInstallSessionState
-dontwarn com.google.android.play.core.splitinstall.SplitInstallStateUpdatedListener
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task

# ── just_audio ────────────────────────────────────────────────────────────────
-keep class com.ryanheise.just_audio.** { *; }

# ── audio_service / just_audio_background ─────────────────────────────────────
# AudioService runs in a foreground service; its class and any serialisation
# helpers must survive shrinking and obfuscation.
-keep class com.ryanheise.audioservice.** { *; }
-dontwarn com.ryanheise.**

# ── ExoPlayer (used internally by just_audio) ─────────────────────────────────
-keep class androidx.media3.** { *; }
-dontwarn androidx.media3.**

# ── Hive (local persistence) ──────────────────────────────────────────────────
# TypeAdapters are discovered by reflection — keep them and their generated
# counterparts intact.
-keep class com.hivedb.** { *; }
-keepclassmembers class * extends com.hivedb.hive.HiveObject { *; }

# ── Kotlin coroutines / serialisation ─────────────────────────────────────────
-keepclassmembernames class kotlinx.** {
    volatile <fields>;
}
-dontwarn kotlinx.coroutines.**

# ── Android Jetpack / AndroidX ────────────────────────────────────────────────
-dontwarn androidx.**

# ── OkHttp / Dio (networking & downloads) ─────────────────────────────────────
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn okhttp3.**
-dontwarn okio.**

# ── Path Provider & URL Launcher ──────────────────────────────────────────────
-keep class io.flutter.plugins.pathprovider.** { *; }
-keep class io.flutter.plugins.urllauncher.** { *; }

# ── General: keep attributes needed for stack-trace de-obfuscation ────────────
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile
